exports.EMAIL = '#email'
exports.PWD = '#password'
exports.SIGNIN = '#signin'
exports.SHOW_ALL_BTN = '.guide-skip-button'
exports.ACTION_ICON_WRAPPER = '[ng-class=actionIconWrapper]'
exports.BALANCE_HERF = '[ng-href="/payment/balance"]'